@startuml
left to right direction
skinparam packageStyle rectangle

actor "Profissional de Saúde" as PS
actor "Vigilância Epidemiológica" as VE
actor "Vigilância Ambiental" as VA

package "LeptoGeo" {
  usecase "Notificar Caso Suspeito" as UC1
  usecase "Registrar Endereço do LPI" as UC1_1
  usecase "Visualizar Mapa de Calor" as UC2
  usecase "Registrar Ação de Controle" as UC3
  usecase "Sinalizar Área Limpa" as UC3_1
  usecase "Acompanhar Prazo (60 dias)" as UC4
  usecase "Inserir Resultado e Encerrar" as UC5

  UC1 .> UC1_1 : \t \t       <<include>>
  UC3_1 .> UC3 :  \t\t\t <<extend>>
}

' Atores do lado esquerdo
PS --> UC1
VE --> UC2
VE --> UC4
VE --> UC5

' Atores do lado direito (Setas invertidas)
UC2 <-- VA
UC3 <-- VA
@enduml